version: "3"
services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: siapbantu
    restart: always
    networks:
      - sb_network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    networks:
      - sb_network
    depends_on:
      - mongo

  geo-service:
    build: geo-service
    container_name: geo-service
    ports:
      - "5000:5000"
    volumes:
      - ./geo-service:/app
    networks:
      - sb_network

  backend-service:
    build:
      context: backend
      dockerfile: Dockerfile.dev
      args:
        NODE_ENV: dev
    container_name: backend-service
    restart: always
    ports:
      - "8000:8000"
      - "9229:9229"
    volumes:
      - ./backend:/app
      - /app/node_modules/
    working_dir: /app
    depends_on:
      - mongo
    networks:
      - sb_network

  client:
    build:
      context: client
      dockerfile: Dockerfile.dev
    restart: always
    container_name: client
    environment:
      BACKEND_SERVICE_URL: http://backend-service:8000
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules/
    working_dir: /app
    stdin_open: true
    tty: true
    networks:
      - sb_network

networks:
  sb_network:
    driver: bridge
