project_categories:
  - name: Medical
    slug: medical
    body: Support our overwhelmed health systems with medical innovation.
    project_types:
      - Scale testing
      - Medical facilities
      - Medical equipments
      - Treatment R&D
    color: purple
  - name: Prevention
    slug: prevention
    body: Inform, reduce, and control the spread of the outbreak.
    project_types:
      - Track the outbreak
      - Reduce spread
    color: orange
  - name: Community
    slug: community
    body: Work together to help our stressed communities.
    project_types:
      - E-Learning
      - Job placement
      - Mental health
      - Help out communities
      - Map volunteers to needs
      - News and information
      - Social giving
    color: blue

global_announcements:
#  - title: Helpful resources for your projects
#    sub_title: We wrote a playbook on how to manage volunteers, had some amazing panels, and gathered some deals for you.
#    cta_text: Browse resources
#    cta_url: /offers

events:
  - title: Lean thinking in a Crisis. Live Panel with Eric Ries
    sub_title: Eric is an entrepreneur and the author of the New York Times bestseller The Lean Startup. He is the creator of the Lean Startup methodology, which has become a global movement in business, practiced by individuals and companies around the world.
    cta_text: View recording
    cta_url: https://drive.google.com/a/openai.com/file/d/1r8PBT_h2ZcnyMExV_hx6B7W8-n35BpgE/view?usp=drive_web
  - title: A Global Perspective on Problems Needing Solutions Regarding COVID-19 Response. Live Panel with Ambika Bumb
    sub_title: Ambika is a Health, Science and Technology Advisor focusing on Crisis Management and Strategy
    cta_text: View recording
    cta_url: https://drive.google.com/a/openai.com/file/d/1I3TjGcWQUsoKGP5dbPT7WD244UjDYiXf/view?usp=drive_web
  - title: Rethinking Resumes | Creating Impact in the age of Insta-everything
    sub_title: Jaimie Lynn Craig Feliz, Founder of The Hire Standard and Bay Area search and resume guru gives actionable insights and tactics to influence, connect and ultimately be seen as the expert you are.
    cta_text: View recording
    cta_url: https://drive.google.com/drive/u/0/folders/13GJiASpNx_FLu3DsMN2pDoExaDrE-J8l
  - title: Sourcing a Volunteer Workforce from TeamBlind’s 3.5MM+ Professionals with Kyum Kim
    sub_title: Tuesday, April 21st 12pm-12:30pm PST
    cta_text: View recording
    cta_url: https://drive.google.com/drive/u/0/folders/1tst9ZLbB7hWGgQE7NpI4P3CjtctI7gT2
  - title: Live panel on Philanthropic Fundraising
    sub_title: Jennifer Pisansky has 10 years of experience in philanthropic fundraising and talks about raising from foundations.
    cta_text: View recording
    cta_url: https://openai.zoom.us/rec/share/3dZaM6vJy1NJfp3c2UHkfa8oQL-7T6a82yRN-fsOmkl9jfRS3GPg-L-gS4Y9zJu3
  - title: Live panel on How to Scale Volunteers
    sub_title: Glen Moriarty, founder of 7cups on how he manages 320k volunteers.
    cta_text: View recording
    cta_url: https://openai.zoom.us/rec/play/vZN-dbuq-m03TNKSsASDAfEtW466J6qs1XQWrvtYxRvmU3QDNVv0NLJGYbffjdiMo1gf68qHVnbe2mOi?continueMode=true
  - title: Live panel on Picking Ideas to Work On
    sub_title: Ivan Gayton, former Head of Mission and Board Member at Doctors without Border, talks about building technology for humanitarian/emergency purposes.
    cta_text: View recording
    cta_url: https://zoom.us/rec/share/5sttA5fAsWxLT6_Nx2-Yd7IEDqfuaaa823JI8_tcyUYSZzIbgvNy717m1UGGegEf
  - title: Live panel on How to Sell and Know Your Audience
    sub_title: ClozeLoop Founders, Hilmon Sorey and Cory Bray, talk about understanding your audience and selling to them.
    cta_text: See slides and recording
    cta_url: https://drive.google.com/drive/u/0/folders/1NATDm5yVsYUo8jRY7svE2fqwm1OwcpMu

upcoming_events:
  - title: Private Group Office Hours with Sam Altman
    sub_title: Three randomly selected Project Owners will have time to discuss their project’s biggest challenges and solicit feedback from Sam.
    month: May
    day: 1
    time: 12:00 PM - 1:00 PM PST
    cta_text: Fill out Form
    cta_url: https://forms.gle/jNFYAd1oLtQjLJrP9
  - title: Private Group Office Hours with Radu
    sub_title: Wednesday, May 6th 3:30pm - 4:30pm
    month: May
    day: 6
    time: 3:30 PM - 4:30 PM PST
    cta_text: Add to Calendar
    cta_url: https://calendar.google.com/event?action=TEMPLATE&tmeid=NWZvanJyZzYybGM2dmhodmc1YmdsNmRpZWcgb3BlbmFpLmNvbV9wOW5mZ2MyZjltcnJkaGE1OW52M2tjYnNya0Bn&tmsrc=openai.com_p9nfgc2f9mrrdha59nv3kcbsrk%40group.calendar.google.com

funding_resources:
  - cta_text: YC S2020 Application
    cta_url: https://www.ycombinator.com/apply/
  - cta_text: WeFunder
    cta_url: https://wefunder.com/raise-money
  - cta_text: 80,000 Hours
    cta_url: https://mailtrack.io/trace/link/8c8d1564095e2d5ec067747e4b3a6f862edfc731?url=https%3A%2F%2F80000hours.org%2F2020%2F04%2Fopportunities-to-work-on-covid-19%2F&userId=2861473&signature=3d3d868b7658ace5
  - cta_text: Association of Fundraising Professionals
    cta_url: https://afpglobal.org/
  - cta_text: Covid Accelerator
    cta_url: https://covidaccelerator.com/
  - cta_text: Covid19-Response
    cta_url: https://www.covid19-response.com/
  - cta_text: Plug and Play
    cta_url: https://www.plugandplaytechcenter.com/covid-19/?utm_campaign=Health_Newsletter_May%202019&utm_source=hs_email&utm_medium=email&utm_content=85778878&_hsenc=p2ANqtz-8AHUCNB-yeVfppjjjjE5b9GKQdFVnuA6FcmSMy3uJOVWtyLW2-DVKL6ybPr8AWWk9VRfO2TotPM8zP-ZUxkNmrusZNqw&_hsmi=85779062
  - cta_text: MIT Covid-19 Research
    cta_url: https://computing.mit.edu/computation-support-covid-19
  - cta_text: H.E.L.P
    cta_url: https://www.helpvolunteer.app/

partner_resources:
  - name: AWS
    description: $10,000 in AWS credits for approved projects. Your project must be a corporate entity. Email siapbantu@gmail.com
    mail_to: helpwithcovid@gmail.com
  - name: ClozeLoop
    description: |+
      Complete Sales Effectiveness Assessments for three companies we choose. The Sales Effectiveness Assessment is an evaluation of your company’s sales Strategy, Systems, Staff and Skills aligned with short and long-term revenue goals. The assessment provides a prioritized high-impact roadmap, and clear recommendations for growth.
      $2500 value.
    cta_link: https://clozeloop.typeform.com/to/ccPwVe
  - name: Turtle Dev
    description: 40 hours of freelance engineering help is available for three companies chosen by the Turtle team. Turtle's developer network is currently specialized to React, React Native, iOS and Android. Based on your project specs and requirements, Turtle will match you with a highly qualified freelance engineer and you'll have full access to the Turtle platform to work together and manage your project. A one hour complimentary product planning session with Turtle's founders will also be available to you.
    cta_link: https://forms.gle/8UaPv6Qjaw8sFBNy9
  - name: Blind
    description: |+
      We are offering promotion at no cost for 4 projects
      - Support 3 projects with native advertising
      - Support 1 project with sponsored AMA post
    cta_link: https://bit.ly/helpwithcovid_blind
